services:
  auton:
    build: .
    image: auton:local
    ports:
      - '127.0.0.1:8666:8666'
    volumes:
      - './etc/auton/docker.yml.example:/etc/auton/auton.yml:ro'
      - 'autond-data:/var/lib/autond'
volumes:
  autond-data:
